Server:
  port: 8001

mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.test.sc.entities
  mapper-locations:
    - classpath:mapper/**/*.xml

spring:
  application:
    name: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: iiiiiUUUUU123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200